// lib/i18n.ts — Traduzioni IT / EN

export type Lang = 'it' | 'en'

export const translations = {
  it: {
    // Nav
    services: 'Servizi',
    properties: 'Immobili',
    contacts: 'Contatti',
    reservedArea: 'Area riservata',
    adminDashboard: 'Dashboard admin',
    manageProperties: 'Gestisci immobili',
    statistics: 'Statistiche visite',
    logout: 'Logout',
    loggedAsAdmin: 'Sei loggato come admin',

    // Hero
    heroTitle1: 'Immobili nel Monferrato,',
    heroTitle2: 'scelti con attenzione',
    discoverProperties: 'Scopri gli immobili',
    contactUs: 'Contattaci',

    // Stats
    yearsInTerritory: 'Anni nel territorio',
    propertiesHandled: 'Immobili trattati',
    satisfiedClients: 'Clienti soddisfatti',
    municipalities: 'Comuni seguiti',

    // Services
    ourServices: 'I nostri servizi',
    serviceSubtitle1: 'Un supporto attento,',
    serviceSubtitle2: "dall'inizio alla fine",
    serviceCopy: 'Lavoriamo con attenzione reale su vendita, acquisto e valorizzazione degli immobili nel Monferrato, con un approccio diretto e senza passaggi inutili.',
    service1Title: 'Selezione accurata',
    service1Body: 'Scegliamo immobili che hanno qualità, identità e potenziale, evitando proposte generiche o poco coerenti.',
    service2Title: 'Conoscenza del territorio',
    service2Body: 'Ti aiutiamo a capire davvero il Monferrato: paesaggio, borghi, valore delle zone e opportunità concrete.',
    service3Title: 'Consulenza chiara',
    service3Body: 'Parliamo in modo semplice e trasparente, così ogni scelta è più consapevole e ogni passaggio più lineare.',

    // Territory
    theTerritory: 'Il territorio',
    livingInMonferrato: 'Vivere nel Monferrato',
    meanChoosing: 'significa scegliere',
    qualityAndCharacter: 'qualità e carattere',
    territoryCopy: 'Colline, vigne, borghi e case con identità. Il nostro lavoro è aiutarti a trovare la proprietà giusta nel contesto giusto, senza perdere tempo in proposte poco adatte.',
    exploreProperties: 'Esplora gli immobili',

    // Featured
    inEvidence: 'In evidenza',
    selectedProposals1: 'Proposte',
    selectedProposals2: 'selezionate',
    viewAll: 'Vedi tutti →',
    discover: 'Scopri',
    featured: 'In evidenza',
    noPropertiesTitle: 'Nessun immobile al momento',
    noPropertiesCopy: 'Stiamo aggiornando il catalogo. Torna presto.',
    noPropertiesAdmin: 'Aggiungi il primo immobile dal pannello admin.',
    addProperty: '+ Aggiungi immobile',

    // Admin quick
    adminArea: 'Area admin',
    manage: 'Gestisci',
    theDashboard: 'la dashboard',
    propertiesCardBody: 'Aggiungi, modifica, metti in evidenza o nascondi i tuoi immobili.',
    goToProperties: 'Vai agli immobili',
    statsCardBody: 'Quante persone hanno visitato il sito e quali immobili hanno guardato.',
    viewStats: 'Vedi statistiche',
    dashboardCardBody: 'Panoramica generale: immobili pubblicati, in evidenza, visite totali.',
    goToDashboard: 'Vai alla dashboard',

    // Testimonials
    testimonials: 'Recensioni',
    whatClients1: 'Cosa dicono',
    whatClients2: 'i nostri clienti',

    // Contacts
    lookingForHouse: 'Cerchi casa nel',
    inMonferrato: 'Monferrato?',
    startHere: 'Partiamo da qui.',
    contactCopy: 'Guarda gli immobili disponibili oppure contattaci direttamente. Ti rispondiamo con indicazioni chiare e senza impegno.',
    whatsapp: 'WhatsApp',
    writeOnWhatsapp: 'Scrivici su WhatsApp',
    mail: 'Mail',
    phone: 'Telefono',
    hours: 'Orari',
    hoursText: 'Lun-Ven 9.00–12.00\nPomeriggio su appuntamento',

    // Filtri affitto/vendita
    filterAll: 'Tutti',
    filterSale: 'Vendita',
    filterRent: 'Affitto',
    forSale: 'Vendita',
    forRent: 'Affitto',
    noPropertiesFilter: 'Nessun immobile per questo filtro.',

    // Property detail
    priceOnRequest: 'Prezzo su richiesta',
    backToList: '← Immobili',
    contactForInfo: 'Contattaci per informazioni',
    whatsappLabel: 'Scrivici su WhatsApp',
    approximatePosition: 'Posizione approssimativa',
    exactPosition: 'Posizione',
    mapNote:
      'Con privacy attiva la mappa è centrata sul comune: “Apri in Google Maps” porta al paese, non al civico.',
    openInGoogleMaps: 'Apri in Google Maps',
    sold: 'Venduto',
    available: 'Disponibile',

    // Immobili listing page
    catalogComplete: 'Catalogo completo',
    allProperties: 'Tutti gli immobili',
    propertiesAvailableCount: 'immobili disponibili',
    soldCount: 'venduti',
    contactForVisits: 'Contattaci per informazioni o sopralluoghi.',
    availableSection: 'Disponibili',
    forRentSection: 'In affitto',
    forSaleSection: 'In vendita',
    propertySingular: 'immobile',
    propertyPlural: 'immobili',
    forSearchLabel: 'per',
    noResultsFor: 'Nessun risultato per',
    tryDifferentSearch: 'Prova con parole chiave diverse.',
    contactCustomSearch: 'Contattaci per ricerche personalizzate.',
    soldSection: 'Venduti',
    discoverCTA: 'Scopri →',
    viewCTA: 'Visualizza →',
    backHome: '← Home',
    listView: 'Lista',
    mapView: 'Mappa',
    searchPlaceholder: 'Cerca per città, titolo…',
    filtersLabel: 'Filtri',
    priceMin: 'Prezzo min (€)',
    priceMax: 'Prezzo max (€)',
    sqmMin: 'Superficie min (m²)',
    resetFilters: 'Reset filtri',

    // Property detail page
    backToAllProperties: '← Tutti gli immobili',
    brandName: 'Monferrato Immobiliare',
    noImageAvailable: 'Nessuna immagine disponibile',
    planimetriaLabel: 'Planimetria',
    planimetriaEmpty: 'Nessuna planimetria disponibile per questo immobile.',
    planimetriaViewPdf: 'Visualizza planimetria (PDF)',
    price: 'Prezzo',
    municipality: 'Comune',
    surface: 'Superficie',
    rooms: 'Locali',
    contract: 'Contratto',
    rentBadge: '🔵 Affitto',
    saleBadge: '🟠 Vendita',
    description: 'Descrizione',
    approximateZone: 'Zona approssimativa',
    requestedPrice: 'Prezzo richiesto',
    contactOnWhatsapp: 'Contatta su WhatsApp',
    whatsappHint: 'Nel messaggio c\'è già il link alla scheda immobile — l\'agente capisce subito di quale annuncio si tratta.',
    agencyName: 'Agenzia Immobiliare Monferrato',
    agencyContactSub: 'Rispondiamo rapidamente a ogni richiesta. Per informazioni più dettagliate scrivici su WhatsApp o torna alla nostra pagina contatti.',
    contactPageLink: 'pagina contatti',
    adminMode: 'Modalità admin',
    editThisProperty: '✏️ Modifica questo immobile',
    adminBarLabel: 'Area Admin',
    addPropertyBtn: '+ Aggiungi immobile',
    contractSale: 'Vendita',
    contractRent: 'Affitto',

    // Footer
    footerRights: 'Tutti i diritti riservati.',
    footerTagline: 'Immobili nel cuore del Monferrato',
    footerPrivacy: 'Privacy Policy',
    footerCookies: 'Cookie Policy',
    footerLogoCaption: "L'Agenzia Immobiliare Monferrato è qui.",
    footerSede: 'Sede',
    footerOpenMaps: 'Google Maps',
    footerWaAria: 'Scrivici su WhatsApp',
  },
  en: {
    // Nav
    services: 'Services',
    properties: 'Properties',
    contacts: 'Contacts',
    reservedArea: 'Reserved area',
    adminDashboard: 'Admin dashboard',
    manageProperties: 'Manage properties',
    statistics: 'Visit statistics',
    logout: 'Logout',
    loggedAsAdmin: 'You are logged in as admin',

    // Hero
    heroTitle1: 'Properties in Monferrato,',
    heroTitle2: 'carefully selected',
    discoverProperties: 'Explore properties',
    contactUs: 'Contact us',

    // Stats
    yearsInTerritory: 'Years in the area',
    propertiesHandled: 'Properties handled',
    satisfiedClients: 'Satisfied clients',
    municipalities: 'Municipalities',

    // Services
    ourServices: 'Our services',
    serviceSubtitle1: 'Dedicated support,',
    serviceSubtitle2: 'from start to finish',
    serviceCopy: 'We work with genuine care on sales, purchases and property enhancement in Monferrato, with a direct approach and no unnecessary steps.',
    service1Title: 'Careful selection',
    service1Body: 'We choose properties with quality, identity and potential, avoiding generic or inconsistent proposals.',
    service2Title: 'Local expertise',
    service2Body: 'We help you truly understand Monferrato: landscape, villages, area value and real opportunities.',
    service3Title: 'Clear advice',
    service3Body: 'We speak plainly and transparently, so every choice is more informed and every step more straightforward.',

    // Territory
    theTerritory: 'The territory',
    livingInMonferrato: 'Living in Monferrato',
    meanChoosing: 'means choosing',
    qualityAndCharacter: 'quality and character',
    territoryCopy: 'Hills, vineyards, villages and homes with identity. Our work is to help you find the right property in the right context, without wasting time on unsuitable proposals.',
    exploreProperties: 'Explore properties',

    // Featured
    inEvidence: 'Featured',
    selectedProposals1: 'Selected',
    selectedProposals2: 'proposals',
    viewAll: 'View all →',
    discover: 'Discover',
    featured: 'Featured',
    noPropertiesTitle: 'No properties at the moment',
    noPropertiesCopy: 'We are updating our catalogue. Please check back soon.',
    noPropertiesAdmin: 'Add the first property from the admin panel.',
    addProperty: '+ Add property',

    // Admin quick
    adminArea: 'Admin area',
    manage: 'Manage',
    theDashboard: 'the dashboard',
    propertiesCardBody: 'Add, edit, feature or hide your properties.',
    goToProperties: 'Go to properties',
    statsCardBody: 'How many people visited the site and which properties they viewed.',
    viewStats: 'View statistics',
    dashboardCardBody: 'General overview: published properties, featured, total visits.',
    goToDashboard: 'Go to dashboard',

    // Testimonials
    testimonials: 'Reviews',
    whatClients1: 'What our',
    whatClients2: 'clients say',

    // Contacts
    lookingForHouse: 'Looking for a home',
    inMonferrato: 'in Monferrato?',
    startHere: "Let's start here.",
    contactCopy: 'Browse available properties or contact us directly. We respond with clear information and no commitment.',
    whatsapp: 'WhatsApp',
    writeOnWhatsapp: 'Write to us on WhatsApp',
    mail: 'Email',
    phone: 'Phone',
    hours: 'Hours',
    hoursText: 'Mon-Fri 9.00–12.00\nAfternoon by appointment',

    // Filtri affitto/vendita
    filterAll: 'All',
    filterSale: 'For sale',
    filterRent: 'For rent',
    forSale: 'For sale',
    forRent: 'For rent',
    noPropertiesFilter: 'No properties for this filter.',

    // Property detail
    priceOnRequest: 'Price on request',
    backToList: '← Properties',
    contactForInfo: 'Contact us for information',
    whatsappLabel: 'Write on WhatsApp',
    approximatePosition: 'Approximate location',
    exactPosition: 'Location',
    mapNote:
      'With privacy on, the map is centred on the municipality: “Open in Google Maps” opens the town, not the exact address.',
    openInGoogleMaps: 'Open in Google Maps',
    sold: 'Sold',
    available: 'Available',

    // Immobili listing page
    catalogComplete: 'Full catalogue',
    allProperties: 'All properties',
    propertiesAvailableCount: 'properties available',
    soldCount: 'sold',
    contactForVisits: 'Contact us for information or viewings.',
    availableSection: 'Available',
    forRentSection: 'For rent',
    forSaleSection: 'For sale',
    propertySingular: 'property',
    propertyPlural: 'properties',
    forSearchLabel: 'for',
    noResultsFor: 'No results for',
    tryDifferentSearch: 'Try different keywords.',
    contactCustomSearch: 'Contact us for personalised searches.',
    soldSection: 'Sold',
    discoverCTA: 'Discover →',
    viewCTA: 'View →',
    backHome: '← Home',
    listView: 'List',
    mapView: 'Map',
    searchPlaceholder: 'Search by city, title…',
    filtersLabel: 'Filters',
    priceMin: 'Min price (€)',
    priceMax: 'Max price (€)',
    sqmMin: 'Min size (m²)',
    resetFilters: 'Reset filters',

    // Property detail page
    backToAllProperties: '← All properties',
    brandName: 'Monferrato Immobiliare',
    noImageAvailable: 'No image available',
    planimetriaLabel: 'Floor plan',
    planimetriaEmpty: 'No floor plan is available for this property.',
    planimetriaViewPdf: 'View floor plan (PDF)',
    price: 'Price',
    municipality: 'Municipality',
    surface: 'Size',
    rooms: 'Rooms',
    contract: 'Contract',
    rentBadge: '🔵 Rental',
    saleBadge: '🟠 Sale',
    description: 'Description',
    approximateZone: 'Approximate area',
    requestedPrice: 'Asking price',
    contactOnWhatsapp: 'Contact on WhatsApp',
    whatsappHint: 'Your message already includes the link to this listing — the agent knows which property you mean.',
    agencyName: 'Monferrato Real Estate',
    agencyContactSub: 'We respond quickly to every enquiry. For more details write to us on WhatsApp or visit our contact page.',
    contactPageLink: 'contact page',
    adminMode: 'Admin mode',
    editThisProperty: '✏️ Edit this property',
    adminBarLabel: 'Admin Area',
    addPropertyBtn: '+ Add property',
    contractSale: 'Sale',
    contractRent: 'Rental',

    // Footer
    footerRights: 'All rights reserved.',
    footerTagline: 'Properties in the heart of Monferrato',
    footerPrivacy: 'Privacy Policy',
    footerCookies: 'Cookie Policy',
    footerLogoCaption: 'Monferrato Immobiliare is here.',
    footerSede: 'Office',
    footerOpenMaps: 'Google Maps',
    footerWaAria: 'Message us on WhatsApp',
  },
} as const

export type TR = typeof translations.it
